apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  concurrency: 10
  metadata:
    tags:
      - e2e
      - release team
      - other tag
playwright:
  version: package.json 
  configFile: playwright.config.ts 

rootDir: ./
suites:
  # - name: "Firefox Win"
  #   platformName: "Windows 11"
  #   screenResolution: "1440x900"
  #   testMatch: ['*.ts']
  #   params:
  #     browserName: "firefox"
  #     project: "firefox"
  # - name: "Chromium Mac"
  #   platformName: "macOS 12"
  #   screenResolution: "1440x900"
  #   testMatch: ['*.ts']
  #   params:
  #     browserName: "chromium"
  #     project: "chromium"
  # - name: "Webkit Win"
  #   platformName: "Windows 11"
  #   screenResolution: "1440x900"
  #   testMatch: ['*.ts']
  #   params:
  #     browserName: "webkit"
  #     project: "webkit"
  - name: "Chromium Win"
    platformName: "Windows 10"
    screenResolution: "1440x900"
    testMatch: ['.*.ts']
    params:
      browserName: "chromium"
      project: "chromium"